---
- meta: flush_handlers
  when: utr_flush_handlers == 'true' and utr_monitor_state != "paused"

- name: "{{ utr_monitor_state }}"
  uptimerobot:
    monitorid: "{{ item }}"
    state: "{{ utr_monitor_state }}"
    apikey: "{{ utr_api_key }}"
  with_items: "{{ utr_monitor_id }}"
  when: utr_api_key and utr_monitor_id and utr_monitor_state
  tags:
    - monitor
