---
- meta: flush_handlers
  when: wtd_utr_flush_handlers == 'true' and wtd_utr_monitor_state != "paused"

- name: "{{ wtd_utr_monitor_state }}"
  uptimerobot:
    monitorid: "{{ item }}"
    state: "{{ wtd_utr_monitor_state }}"
    apikey: "{{ wtd_utr_api_key }}"
  with_items: "{{ wtd_utr_monitor_id }}"
  when: wtd_utr_api_key and wtd_utr_monitor_id and wtd_utr_monitor_state
  tags:
    - monitor
